### ISSUE TITLE
Add Application target to project

### ISSUE THREAD

**Issue by mats-claassen** [thoughtbot/liftoff#262]
Hi Is there a way to add an application target (executable)?
For example I want this second "qwe Staging" target
![screenshot](https://cloud.githubusercontent.com/assets/8573865/11531491/f332ed68-98db-11e5-9e71-076a1086b3ee.png)

Thanks in advance!

**Comment by jakecraige** [comment]
Yes you can configure that via a [liftoffrc](https://github.com/thoughtbot/liftoff#configuration). Specifically you'll use the `app_target_templates` key to specify a new target. See the [default liftoffrc](https://github.com/thoughtbot/liftoff/blob/master/defaults/liftoffrc#L64-L102) for an example.

**Comment by mats-claassen** [comment]
Sorry but I could still not make it work.
If i put something like this
```
swift:
    - <%= project_name %>:
      - Extensions:
      - Protocols:
      ......
   - <%= project_name %>-Development:
      - Extensions:
      - Protocols:
      ......
```
Then it will just create two folders but not two targets.
And in addition to this, can I link this target to a custom scheme?
